WEProjectUniversitySearchPortal/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEProjectUniversitySearchPortal.Models;
using System.Data.SqlClient;

namespace WEProjectUniversitySearchPortal.Controllers
{
    public class CoursesController : Controller
    {
        static public String constr = @"Data Source=DESKTOP-E188SG7\SQLSERVER2019;Initial Catalog=universityPortal;Integrated Security=true";
        static public SqlConnection con = new SqlConnection(constr);
        // GET: Courses
        public ActionResult Courses()
        {
            ViewBag.msg = "";
            return View();
        }
        [HttpPost]
        public ActionResult Courses(Courses c)
        {
            try
            {
                con.Open();
                String querry = @"insert into courses values('" + c.u_id + "','" + c.p_id + "','" + c.name + "','" +c.crhs+ "','" +c.c_code+ "')";
                SqlCommand cmd = new SqlCommand(querry, con);
                cmd.ExecuteNonQuery();
                con.Close();
                ViewBag.msg = "Success";
            }
            catch (Exception ex)
            {
                ViewBag.msg = ex.Message;
            }
            return View();
        }
        public ActionResult AllCourses(String uniId,String uname,String programId, String programname)
        {
            var list = readingAllCourses(uniId, programId);
            return View(list);
        }
        public List<Courses> readingAllCourses(String uniId,String pId)
        {
            String querry = @"select * from courses where u_id='"+uniId+"' and p_id='"+pId+"'";
            con.Open();
            SqlCommand smd = new SqlCommand(querry, con);
            SqlDataReader sdr = smd.ExecuteReader();
            List<Courses> plist = new List<Courses>();
            while (sdr.Read())
            {
                Courses c = new Courses();
                c.c_id = sdr["c_id"].ToString();
                c.u_id = sdr["u_id"].ToString();
                c.p_id = sdr["p_id"].ToString();
                c.name = sdr["cname"].ToString();
                c.crhs = sdr["chrs"].ToString();
                c.c_code = sdr["c_code"].ToString();
                plist.Add(c);
            }
            con.Close();
            return plist;
        }
    }
}

WEProjectUniversitySearchPortal/Controllers/FacultyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEProjectUniversitySearchPortal.Models;
using System.Data.SqlClient;
using System.IO;


namespace WEProjectUniversitySearchPortal.Controllers
{
    public class FacultyController : Controller
    {
        static public String constr = @"Data Source=DESKTOP-E188SG7\SQLSERVER2019;Initial Catalog=universityPortal;Integrated Security=true";
        static public SqlConnection con = new SqlConnection(constr);
        // GET: Faculty
        public ActionResult Faculty()
        {
            ViewBag.path = null;
            return View();
        }
        [HttpPost]
        public ActionResult Faculty(Faculty f)
        {
            try
            {
                var aext = new[] { ".png", ".jpeg", ".jpg", ".bnp" };
                var ext = Path.GetExtension(f.fimage.FileName);
                var imageName =f.name + "_" + f.u_id + ext;
                if (aext.Contains(ext))
                {
                    var path = Path.Combine(Server.MapPath("~/images/"), imageName);
                    f.fimage.SaveAs(path);
                    var pathToDatabae = "/images/" + imageName;
                    con.Open();
                    String querry = "insert into faculties values('" + f.u_id + "','" + f.name + "','" + f.experience + "','" + pathToDatabae + "')";
                    SqlCommand cmd = new SqlCommand(querry, con);
                    cmd.ExecuteNonQuery();
                    con.Close();
                    ViewBag.path = "Saved Successfully" + path;
                }
            }
            catch (Exception ex)
            {
                ViewBag.path = ex.Message;
            }
            return View();
        }
        [HttpGet]
        public ActionResult AllFaculty(String uniId, String uname)
        {
            var list = readingFaculty(uniId);
            return View(list);

        }


        #region private functions
        private List<Faculty> readingFaculty(String uId)
        {
            con.Open();
            String querry = @"select * from faculties where u_id='"+uId+"'";
            SqlCommand cmd = new SqlCommand(querry, con);
            SqlDataReader sdr = cmd.ExecuteReader();
            List<Faculty> lfaculty = new List<Faculty>();
            while (sdr.Read())
            {
                Faculty f = new Faculty();
                f.u_id = sdr["u_id"].ToString();
                f.f_id = sdr["f_id"].ToString();
                f.name = sdr["fname"].ToString();
                f.experience = sdr["experience"].ToString();
                f.fpath = sdr["fimage"].ToString();
                lfaculty.Add(f);
            }
            con.Close();
            return lfaculty;
        }


        #endregion

    }
}

WEProjectUniversitySearchPortal/Controllers/ProgramController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WEProjectUniversitySearchPortal.Models;
using System.Data.SqlClient;


namespace WEProjectUniversitySearchPortal.Controllers
{
    public class ProgramController : Controller
    {
        static public String constr = @"Data Source=DESKTOP-E188SG7\SQLSERVER2019;Initial Catalog=universityPortal;Integrated Security=true";
        static public SqlConnection con = new SqlConnection(constr);
        // GET: Program
        public ActionResult Program()
        {
            ViewBag.msg = "";
            return View();
        }
        [HttpPost]
        public ActionResult Program(Program p)
        {
            try
            {
                con.Open();
                String querry = @"insert into programs values('"+p.u_id+ "','"+p.pName+ "','"+p.requirements+"')";
                SqlCommand cmd = new SqlCommand(querry,con);
                cmd.ExecuteNonQuery();
                con.Close();
                ViewBag.msg = "Success";
            }
            catch (Exception ex)
            {
                ViewBag.msg = ex.Message;
            }
            return View();
        }
        [HttpGet]
        public ActionResult AllPrograms(String uniId, String uname)
        {
            var plist = readingAllPrograms(uniId);
            return View(plist);
        }

        #region private functions
        public List<Program> readingAllPrograms(String uniId)
        {
            String querry = @"select * from programs where u_id='"+uniId+"'";
            con.Open();
            SqlCommand smd = new SqlCommand(querry, con);
            SqlDataReader sdr = smd.ExecuteReader();
            List<Program> plist = new List<Program>();
            while (sdr.Read())
            {
                Program p = new Program();
                p.u_id = sdr["u_id"].ToString();
                p.p_id = sdr["p_id"].ToString();
                p.pName = sdr["pname"].ToString();
                p.requirements = sdr["prequirements"].ToString();
                plist.Add(p);
            }
            con.Close();
            return plist;
        }

        #endregion
    }
}

WEProjectUniversitySearchPortal/Controllers/UniversityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using WEProjectUniversitySearchPortal.Models;
using System.Data.SqlClient;

namespace WEProjectUniversitySearchPortal.Controllers
{
    public class UniversityController : Controller
    {
        static public String constr = @"Data Source=DESKTOP-E188SG7\SQLSERVER2019;Initial Catalog=universityPortal;Integrated Security=true";
        static public SqlConnection con = new SqlConnection(constr);
        // GET: University
        [HttpGet]
        public ActionResult AllUniversities()
        {
            var uList = gettingAllUniversities();
            return View(uList);
        }
        [HttpPost]
        public ActionResult AllUniversities(String uniSearch)
        {
            var uList = gettingAllUniversities(uniSearch);
            return View(uList);
        }
        #region getting All universities
        private List<University> gettingAllUniversities()
        {
            con.Open();
            String querry = "select * from universities";
            SqlCommand cmd = new SqlCommand(querry, con);
            SqlDataReader sdr = cmd.ExecuteReader();
            List<University> uList = new List<University>();
            while (sdr.Read())
            {
                University u = new University();
                u.u_id = sdr["u_id"].ToString();
                u.name = sdr["name"].ToString();
                u.location = sdr["location"].ToString();
                u.registered = sdr["registered"].ToString();
                u.path = sdr["image"].ToString();
                uList.Add(u);
            }
            con.Close();
            return uList;
        }
        private List<University> gettingAllUniversities(String search)
        {
            con.Open();
            String querry = "select * from universities where location='" + search + "'";
            SqlCommand cmd = new SqlCommand(querry, con);
            SqlDataReader sdr = cmd.ExecuteReader();
            List<University> uList = new List<University>();
            while (sdr.Read())
            {
                University u = new University();
                u.u_id = sdr["u_id"].ToString();
                u.name = sdr["name"].ToString();
                u.location = sdr["location"].ToString();
                u.registered = sdr["registered"].ToString();
                u.path = sdr["image"].ToString();
                uList.Add(u);
            }
            con.Close();
            return uList;
        }
        #endregion
        [HttpGet]
        public ActionResult University()
        {
            ViewBag.path = null;
            return View();
        }
        [HttpPost]
        public ActionResult University(University u)
        {

            try
            {
                var aext = new[] { ".png", ".jpeg", ".jpg", ".bnp" };
                var ext = Path.GetExtension(u.image.FileName);
                var imageName = u.name + "_" + u.location + ext;
                if (aext.Contains(ext))
                {
                    var path = Path.Combine(Server.MapPath("~/images/"), imageName);
                    u.image.SaveAs(path);
                    var pathToDatabae = "/images/" + imageName;
                    con.Open();
                    String querry = "insert into universities values('" + u.name + "','" + u.location + "','" + u.registered + "','" + pathToDatabae + "')";
                    SqlCommand cmd = new SqlCommand(querry, con);
                    cmd.ExecuteNonQuery();
                    con.Close();
                    ViewBag.path = "Saved Successfully" + path;
                }
            } catch (Exception ex)
            {
                ViewBag.path = ex.Message;
            }
            return View();
        }
        [HttpGet]
        public ActionResult SelectedUniversity(String uniId, String uname)
        {
            return View();   
        }
       

        private void readingFacultyOfUni(String uniId)
        {
            String querry = "select * from faculties where u_id='" + uniId + "'";
            SqlCommand cmd = new SqlCommand(querry, con);
            SqlDataReader sdr = cmd.ExecuteReader();

        }
        private void readingProgramOfUni()
        {

        }
    }
}

WEProjectUniversitySearchPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" href="~/img/apple-icon.png">
    <link rel="shortcut icon" type="image/x-icon" href="">

    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/templatemo.css">
    <link rel="stylesheet" href="~/css/custom.css">

    <!-- Load fonts style after rendering the layout styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="~/css/fontawesome.min.css">
</head>
<body>
    <!-- Start Top Nav -->
    <nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block" id="templatemo_nav_top">
        <div class="container text-light">
            <div class="w-100 d-flex justify-content-between">
                <div>
                    <i class="fa fa-envelope mx-2"></i>
                    <a class="navbar-sm-brand text-light text-decoration-none" href="mailto:info@company.com">info@company.com</a>
                    <i class="fa fa-phone mx-2"></i>
                    <a class="navbar-sm-brand text-light text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
                </div>
                <div>
                    <a class="text-light" href="https://fb.com/templatemo" target="_blank" rel="sponsored"><i class="fab fa-facebook-f fa-sm fa-fw me-2"></i></a>
                    <a class="text-light" href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram fa-sm fa-fw me-2"></i></a>
                    <a class="text-light" href="https://twitter.com/" target="_blank"><i class="fab fa-twitter fa-sm fa-fw me-2"></i></a>
                    <a class="text-light" href="https://www.linkedin.com/" target="_blank"><i class="fab fa-linkedin fa-sm fa-fw"></i></a>
                </div>
            </div>
        </div>
    </nav>

    <!-- Close Top Nav -->
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light shadow">
        <div class="container d-flex justify-content-between align-items-center">

            <a class="navbar-brand text-success logo h1 align-self-center" href="index.html">
                USP
            </a>

            <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
                <div class="flex-fill">
                    <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="index.html">@Html.ActionLink("Home", "Index", "Home")</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="contact.html">@Html.ActionLink("Universities", "UniversitySearchInCity", "University")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="about.html">@Html.ActionLink("About", "About", "Home")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="contact.html">@Html.ActionLink("Contact", "Contact", "Home")</a>
                        </li>
                        <li class="nav-link">@Html.ActionLink("Add university", "University", "University")</li>
                        <li class="nav-link">@Html.ActionLink("All university", "AllUniversities", "University")</li>
                        <li class="nav-link">@Html.ActionLink("Add Faculty", "Faculty", "Faculty")</li>
                        <li class="nav-link">@Html.ActionLink("All Faculty", "AllFaculty", "Faculty")</li>
                        <li class="nav-link">@Html.ActionLink("Add Programs", "Program", "Program")</li>
                        <li class="nav-link">@Html.ActionLink("All Programs", "AllPrograms", "Program")</li>
                        <li class="nav-link">@Html.ActionLink("Add Courses", "Courses", "Courses")</li>




                    </ul>
                </div>

            </div>

        </div>
    </nav>
    <!-- Close Header -->
    <div>
        @RenderBody()

    </div>



    <!-- Start Footer -->
    <footer class="bg-dark" id="tempaltemo_footer">
        <div class="container">
            <div class="row">

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-success border-bottom pb-3 border-light logo">Zay Shop</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li>
                            <i class="fas fa-map-marker-alt fa-fw"></i>
                            123 Consectetur at ligula 10660
                        </li>
                        <li>
                            <i class="fa fa-phone fa-fw"></i>
                            <a class="text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
                        </li>
                        <li>
                            <i class="fa fa-envelope fa-fw"></i>
                            <a class="text-decoration-none" href="mailto:info@company.com">info@company.com</a>
                        </li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Products</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" href="#">Luxury</a></li>
                        <li><a class="text-decoration-none" href="#">Sport Wear</a></li>
                        <li><a class="text-decoration-none" href="#">Men's Shoes</a></li>
                        <li><a class="text-decoration-none" href="#">Women's Shoes</a></li>
                        <li><a class="text-decoration-none" href="#">Popular Dress</a></li>
                        <li><a class="text-decoration-none" href="#">Gym Accessories</a></li>
                        <li><a class="text-decoration-none" href="#">Sport Shoes</a></li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Further Info</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" href="#">Home</a></li>
                        <li><a class="text-decoration-none" href="#">About Us</a></li>
                        <li><a class="text-decoration-none" href="#">Shop Locations</a></li>
                        <li><a class="text-decoration-none" href="#">FAQs</a></li>
                        <li><a class="text-decoration-none" href="#">Contact</a></li>
                    </ul>
                </div>

            </div>

            <div class="row text-light mb-4">
                <div class="col-12 mb-3">
                    <div class="w-100 my-3 border-top border-light"></div>
                </div>
                <div class="col-auto me-auto">
                    <ul class="list-inline text-left footer-icons">
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="http://facebook.com/"><i class="fab fa-facebook-f fa-lg fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://www.instagram.com/"><i class="fab fa-instagram fa-lg fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://twitter.com/"><i class="fab fa-twitter fa-lg fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://www.linkedin.com/"><i class="fab fa-linkedin fa-lg fa-fw"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-auto">
                    <label class="sr-only" for="subscribeEmail">Email address</label>
                    <div class="input-group mb-2">
                        <input type="text" class="form-control bg-dark border-light" id="subscribeEmail" placeholder="Email address">
                        <div class="input-group-text btn-success text-light">Subscribe</div>
                    </div>
                </div>
            </div>
        </div>



    </footer>
    <!-- End Footer -->
    <!-- Start Script -->
    <script src="~/js/jquery-1.11.0.min.js"></script>
    <script src="~/js/jquery-migrate-1.2.1.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/templatemo.js"></script>
    <script src="~/js/custom.js"></script>
    <!-- End Script -->
</body>

</html>